import js from '@eslint/js';
import ts from 'typescript-eslint';
import svelte from 'eslint-plugin-svelte';
import prettier from 'eslint-config-prettier';

/** @type {import('eslint').Linter.Config[]} */
export default [
  {
    ignores: [
      '**/build/**',
      '**/.svelte-kit/**',
      '**/dist/**',
      '**/node_modules/**',
      '**/*.d.ts',
      '.turbo/**',
      '.auto-claude/**',
    ],
  },
  js.configs.recommended,
  ...ts.configs.recommended,
  ...svelte.configs['flat/recommended'],
  prettier,
  {
    files: ['**/*.svelte'],
    languageOptions: {
      parserOptions: {
        parser: ts.parser,
        svelteFeatures: {
          // Enable Svelte 5 runes support
          runes: true,
        },
      },
      globals: {
        // Browser globals
        window: 'readonly',
        document: 'readonly',
        navigator: 'readonly',
        localStorage: 'readonly',
        sessionStorage: 'readonly',
        history: 'readonly',
        location: 'readonly',
        fetch: 'readonly',
        URL: 'readonly',
        URLSearchParams: 'readonly',
        Request: 'readonly',
        Response: 'readonly',
        Headers: 'readonly',
        FormData: 'readonly',
        Blob: 'readonly',
        File: 'readonly',
        FileReader: 'readonly',
        AbortController: 'readonly',
        AbortSignal: 'readonly',
        Event: 'readonly',
        EventTarget: 'readonly',
        MouseEvent: 'readonly',
        KeyboardEvent: 'readonly',
        FocusEvent: 'readonly',
        InputEvent: 'readonly',
        SubmitEvent: 'readonly',
        DragEvent: 'readonly',
        ClipboardEvent: 'readonly',
        WheelEvent: 'readonly',
        UIEvent: 'readonly',
        ProgressEvent: 'readonly',
        CustomEvent: 'readonly',
        MediaQueryList: 'readonly',
        MediaQueryListEvent: 'readonly',
        HTMLElement: 'readonly',
        HTMLAnchorElement: 'readonly',
        HTMLAreaElement: 'readonly',
        HTMLAudioElement: 'readonly',
        HTMLBaseElement: 'readonly',
        HTMLBodyElement: 'readonly',
        HTMLBRElement: 'readonly',
        HTMLButtonElement: 'readonly',
        HTMLCanvasElement: 'readonly',
        HTMLDataElement: 'readonly',
        HTMLDataListElement: 'readonly',
        HTMLDetailsElement: 'readonly',
        HTMLDialogElement: 'readonly',
        HTMLDivElement: 'readonly',
        HTMLDListElement: 'readonly',
        HTMLEmbedElement: 'readonly',
        HTMLFieldSetElement: 'readonly',
        HTMLFormElement: 'readonly',
        HTMLHeadingElement: 'readonly',
        HTMLHRElement: 'readonly',
        HTMLHtmlElement: 'readonly',
        HTMLIFrameElement: 'readonly',
        HTMLImageElement: 'readonly',
        HTMLInputElement: 'readonly',
        HTMLLabelElement: 'readonly',
        HTMLLegendElement: 'readonly',
        HTMLLIElement: 'readonly',
        HTMLLinkElement: 'readonly',
        HTMLMapElement: 'readonly',
        HTMLMenuElement: 'readonly',
        HTMLMetaElement: 'readonly',
        HTMLMeterElement: 'readonly',
        HTMLModElement: 'readonly',
        HTMLOListElement: 'readonly',
        HTMLObjectElement: 'readonly',
        HTMLOptGroupElement: 'readonly',
        HTMLOptionElement: 'readonly',
        HTMLOutputElement: 'readonly',
        HTMLParagraphElement: 'readonly',
        HTMLParamElement: 'readonly',
        HTMLPictureElement: 'readonly',
        HTMLPortalElement: 'readonly',
        HTMLPreElement: 'readonly',
        HTMLProgressElement: 'readonly',
        HTMLQuoteElement: 'readonly',
        HTMLScriptElement: 'readonly',
        HTMLSelectElement: 'readonly',
        HTMLSlotElement: 'readonly',
        HTMLSourceElement: 'readonly',
        HTMLSpanElement: 'readonly',
        HTMLStyleElement: 'readonly',
        HTMLTableCaptionElement: 'readonly',
        HTMLTableCellElement: 'readonly',
        HTMLTableColElement: 'readonly',
        HTMLTableElement: 'readonly',
        HTMLTableRowElement: 'readonly',
        HTMLTableSectionElement: 'readonly',
        HTMLTemplateElement: 'readonly',
        HTMLTextAreaElement: 'readonly',
        HTMLTimeElement: 'readonly',
        HTMLTitleElement: 'readonly',
        HTMLTrackElement: 'readonly',
        HTMLUListElement: 'readonly',
        HTMLUnknownElement: 'readonly',
        HTMLVideoElement: 'readonly',
        SVGElement: 'readonly',
        SVGSVGElement: 'readonly',
        setTimeout: 'readonly',
        clearTimeout: 'readonly',
        setInterval: 'readonly',
        clearInterval: 'readonly',
        requestAnimationFrame: 'readonly',
        cancelAnimationFrame: 'readonly',
        requestIdleCallback: 'readonly',
        cancelIdleCallback: 'readonly',
        console: 'readonly',
        TextEncoder: 'readonly',
        TextDecoder: 'readonly',
        atob: 'readonly',
        btoa: 'readonly',
        structuredClone: 'readonly',
        crypto: 'readonly',
        CSS: 'readonly',
        CSSRule: 'readonly',
        CSSStyleDeclaration: 'readonly',
        IntersectionObserver: 'readonly',
        IntersectionObserverEntry: 'readonly',
        ResizeObserver: 'readonly',
        MutationObserver: 'readonly',
        Performance: 'readonly',
        PerformanceEntry: 'readonly',
        PerformanceObserver: 'readonly',
      },
    },
    rules: {
      // Disable parsing errors for Svelte 5 syntax that parser doesn't fully support yet
      '@typescript-eslint/no-unused-vars': 'off',
      'svelte/no-navigation-without-resolve': 'off',
      'no-undef': 'off',
      'svelte/prefer-writable-derived': 'off',
      'svelte/require-each-key': 'off',
    },
  },
  {
    languageOptions: {
      globals: {
        node: true,
        process: 'readonly',
        Buffer: 'readonly',
      },
    },
    rules: {
      '@typescript-eslint/no-unused-vars': ['warn', { argsIgnorePattern: '^_' }],
      '@typescript-eslint/no-explicit-any': 'warn',
      'svelte/no-at-html-tags': 'warn',
      'svelte/no-navigation-without-resolve': 'off',
      'no-empty': 'off',
      'no-extra-boolean-cast': 'off',
    },
  },
];
