name: 🐛 Bug Report
description: Something isn't working
labels: ['bug', 'needs-triage']
body:
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I searched existing issues and this hasn't been reported
          required: true

  - type: dropdown
    id: area
    attributes:
      label: Area
      options:
        - Frontend
        - Backend
        - Fullstack
        - Not sure
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version
      placeholder: 'e.g., 0.0.17'
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: Describe the bug clearly and concisely. Include any error messages.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs / Screenshots
      description: Required for UI bugs. Attach relevant logs or screenshots.
      render: shell
