name: ✨ Feature Request
description: Suggest a new feature
labels: ['feature', 'needs-triage']
body:
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have checked existing issues to make sure this feature hasn't been requested
          required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - priority/critical
        - priority/high
        - priority/medium
        - priority/low
    validations:
      required: true

  - type: dropdown
    id: area
    attributes:
      label: Area
      options:
        - Frontend
        - Backend
        - Fullstack
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: A clear and concise description of the feature you'd like to see
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What pain point does it address?
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see in detail

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Describe any alternative solutions you've considered

  - type: checkboxes
    id: contribute
    attributes:
      label: Contribution
      options:
        - label: I'm willing to submit a PR for this
