name: ❓ Question
description: Needs clarification
labels: ['question', 'needs-triage']
body:
  - type: markdown
    attributes:
      value: |
        **Before asking:** Check existing issues and documentation - your question may already be answered!

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I searched existing issues and documentation for similar questions
          required: true

  - type: dropdown
    id: area
    attributes:
      label: Area
      options:
        - Setup/Installation
        - Frontend
        - Backend
        - Configuration
        - Development
        - Other
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version
      description: Which version are you using?
      placeholder: 'e.g., 0.0.17'

  - type: textarea
    id: question
    attributes:
      label: Question
      description: Describe your question in detail
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: What are you trying to achieve?
    validations:
      required: true

  - type: textarea
    id: attempts
    attributes:
      label: What have you already tried?
      description: What steps have you taken to resolve this?
